import type { Stepbook } from "../types"

export const pythonStepbooks: Stepbook[] = [
  {
    id: "python/install-and-run",
    language: "python",
    taskClass: "install-and-run",
    triggers: ["install", "run", "start", "setup", "execute", "launch"],
    description: "Install dependencies and run a Python application",
    steps: [
      { order: 1, action: "Detect Python version", command: "python3 --version", validate: "Should return Python 3.x" },
      { order: 2, action: "Check for existing venv", command: "ls -la .venv/ || ls -la venv/", fallback: "Create venv: python3 -m venv .venv" },
      { order: 3, action: "Activate venv", command: "source .venv/bin/activate" },
      { order: 4, action: "Detect dependency file", command: "ls pyproject.toml requirements.txt setup.py Pipfile 2>/dev/null", validate: "At least one dependency file found" },
      { order: 5, action: "Install dependencies", command: "pip install -r requirements.txt (or pip install -e '.[dev]' for pyproject.toml)", validate: "No errors during install" },
      { order: 6, action: "Detect entry point", command: "Check pyproject.toml [project.scripts], setup.py entry_points, or __main__.py", validate: "Entry point identified" },
      { order: 7, action: "Run the application", command: "python -m <package> OR python <script.py>", validate: "Application starts without ImportError or ModuleNotFoundError" },
    ],
  },
  {
    id: "python/fix-pytest-failures",
    language: "python",
    taskClass: "fix-test",
    triggers: ["test", "pytest", "failing", "broken test", "test failure"],
    description: "Diagnose and fix pytest test failures",
    steps: [
      { order: 1, action: "Run pytest with verbose output", command: "python -m pytest -xvs --tb=short", validate: "Get clear error output" },
      { order: 2, action: "Identify failure type", command: "Read the FAILED line and assertion error", validate: "Classified as: assertion / import / fixture / runtime" },
      { order: 3, action: "Check imports", command: "Verify all test imports resolve", fallback: "pip install -e . for local packages" },
      { order: 4, action: "Read the failing test code", command: "Open the test file at the failing line" },
      { order: 5, action: "Read the code under test", command: "Open the source file referenced by the failure" },
      { order: 6, action: "Fix the root cause", command: "Edit source or test based on diagnosis" },
      { order: 7, action: "Re-run failing test only", command: "python -m pytest <test_file>::<test_name> -xvs", validate: "Test passes" },
      { order: 8, action: "Run full suite", command: "python -m pytest", validate: "All tests pass" },
    ],
  },
  {
    id: "python/add-cli-command",
    language: "python",
    taskClass: "add-cli",
    triggers: ["cli", "command", "argparse", "click", "typer", "add command"],
    description: "Add a new CLI command to a Python application",
    steps: [
      { order: 1, action: "Detect CLI framework", command: "grep -r 'click\\|typer\\|argparse\\|fire' *.py src/ --include='*.py' -l", validate: "Framework identified" },
      { order: 2, action: "Find existing CLI entry point", command: "Check pyproject.toml [project.scripts] or setup.py console_scripts" },
      { order: 3, action: "Study existing command pattern", command: "Read an existing command for style reference" },
      { order: 4, action: "Create the new command", command: "Follow existing pattern — same decorator style, error handling, output format" },
      { order: 5, action: "Wire the command", command: "Register in the CLI group/app object" },
      { order: 6, action: "Test the command", command: "python -m <package> <new-command> --help", validate: "Help text shows up" },
      { order: 7, action: "Add a test", command: "Write a test following existing test patterns" },
    ],
  },
  {
    id: "python/fix-import-path",
    language: "python",
    taskClass: "fix-import",
    triggers: ["import", "ModuleNotFoundError", "ImportError", "cannot import", "no module named"],
    description: "Fix Python import path issues",
    steps: [
      { order: 1, action: "Read the exact error message", command: "Capture the import error traceback" },
      { order: 2, action: "Verify the module exists", command: "find . -name '<module>.py' -o -name '<module>' -type d" },
      { order: 3, action: "Check package structure", command: "Verify __init__.py exists in every directory between root and target" },
      { order: 4, action: "Check sys.path", command: "python -c 'import sys; print(\"\\n\".join(sys.path))'", validate: "Project root should be in sys.path" },
      { order: 5, action: "Check editable install", command: "pip show <package-name>", fallback: "pip install -e ." },
      { order: 6, action: "Fix the import", command: "Use absolute import from package root, or fix relative import" },
      { order: 7, action: "Verify fix", command: "python -c 'from <package> import <module>'", validate: "No ImportError" },
    ],
  },
  {
    id: "python/package-local-module",
    language: "python",
    taskClass: "package-module",
    triggers: ["package", "module", "setup.py", "pyproject.toml", "editable install", "pip install -e"],
    description: "Package a local Python module for installation",
    steps: [
      { order: 1, action: "Check existing packaging", command: "ls pyproject.toml setup.py setup.cfg 2>/dev/null" },
      { order: 2, action: "Identify package directory", command: "Find the main source directory with __init__.py" },
      { order: 3, action: "Create or update pyproject.toml", command: "Add [build-system], [project] with name, version, dependencies" },
      { order: 4, action: "Add __init__.py files", command: "Ensure all package directories have __init__.py" },
      { order: 5, action: "Install in editable mode", command: "pip install -e '.[dev]'", validate: "Installation succeeds" },
      { order: 6, action: "Verify imports work", command: "python -c 'import <package>'", validate: "No errors" },
      { order: 7, action: "Run tests", command: "python -m pytest", validate: "All imports resolve" },
    ],
  },
]
