import type { Stepbook } from "../types"

export const typescriptStepbooks: Stepbook[] = [
  {
    id: "typescript/install-and-run",
    language: "typescript",
    taskClass: "install-and-run",
    triggers: ["install", "run", "start", "setup", "launch", "dev server"],
    description: "Install dependencies and run a TypeScript application",
    steps: [
      { order: 1, action: "Detect package manager", command: "ls bun.lockb pnpm-lock.yaml yarn.lock package-lock.json 2>/dev/null", validate: "Lockfile found → use that manager" },
      { order: 2, action: "Check Node/Bun version", command: "node --version (or bun --version)", validate: "Version meets package.json engines requirement" },
      { order: 3, action: "Install dependencies", command: "<pm> install (npm/pnpm/bun/yarn)", validate: "No errors, lockfile updated" },
      { order: 4, action: "Check for build step", command: "Read package.json scripts for 'build' or 'dev'", validate: "Script exists" },
      { order: 5, action: "Check environment variables", command: "ls .env.example .env.local 2>/dev/null", fallback: "cp .env.example .env" },
      { order: 6, action: "Start dev server", command: "<pm> run dev", validate: "Server starts, no crash on first request" },
      { order: 7, action: "Verify in browser or curl", command: "curl http://localhost:<port>", validate: "Response received" },
    ],
  },
  {
    id: "typescript/fix-build-error",
    language: "typescript",
    taskClass: "fix-build",
    triggers: ["build", "tsc", "compile", "build error", "type error"],
    description: "Diagnose and fix TypeScript build errors",
    steps: [
      { order: 1, action: "Run typecheck", command: "tsc --noEmit 2>&1 | head -50", validate: "Capture all errors" },
      { order: 2, action: "Count and classify errors", command: "Group by error code (TS2307, TS2345, etc.)" },
      { order: 3, action: "Fix dependency errors first (TS2307)", command: "Install missing packages or fix import paths" },
      { order: 4, action: "Fix type assignment errors (TS2322, TS2345)", command: "Update types to match expected interfaces" },
      { order: 5, action: "Fix property access errors (TS2339)", command: "Add missing properties or use type guards" },
      { order: 6, action: "Re-run typecheck", command: "tsc --noEmit", validate: "Zero errors" },
      { order: 7, action: "Run build", command: "<pm> run build", validate: "Build succeeds" },
    ],
  },
  {
    id: "typescript/fix-type-error",
    language: "typescript",
    taskClass: "fix-type",
    triggers: ["type error", "type mismatch", "not assignable", "TS2345", "TS2322", "TS2339"],
    description: "Fix a specific TypeScript type error",
    steps: [
      { order: 1, action: "Read the full error message", command: "Capture TS error code, file, line, source and target types" },
      { order: 2, action: "Open the error location", command: "Read the file at the failing line" },
      { order: 3, action: "Trace the type definitions", command: "Find the type/interface definitions for both source and target" },
      { order: 4, action: "Identify the mismatch", command: "Compare properties, check for optional vs required, union types, generics" },
      { order: 5, action: "Fix the type", command: "Update the type, add type guard, or fix the value — NOT by using `as any`" },
      { order: 6, action: "Verify fix", command: "tsc --noEmit", validate: "Error resolved, no new errors introduced" },
    ],
  },
  {
    id: "typescript/fix-dev-server",
    language: "typescript",
    taskClass: "fix-dev-server",
    triggers: ["dev server", "localhost", "port", "vite", "next", "server crash", "EADDRINUSE"],
    description: "Fix a broken TypeScript dev server",
    steps: [
      { order: 1, action: "Check if port is in use", command: "lsof -i :<port> 2>/dev/null", fallback: "Kill the process or use a different port" },
      { order: 2, action: "Clear caches", command: "rm -rf .next .nuxt node_modules/.cache node_modules/.vite" },
      { order: 3, action: "Check config files", command: "Read vite.config.ts / next.config.js for syntax errors" },
      { order: 4, action: "Check environment variables", command: "Verify .env files exist and are valid" },
      { order: 5, action: "Reinstall dependencies", command: "<pm> install", validate: "Clean install succeeds" },
      { order: 6, action: "Start dev server", command: "<pm> run dev", validate: "Server starts without errors" },
      { order: 7, action: "Test with request", command: "curl http://localhost:<port>", validate: "Response received" },
    ],
  },
  {
    id: "typescript/add-route-component",
    language: "typescript",
    taskClass: "add-component",
    triggers: ["route", "component", "page", "endpoint", "api handler", "add page"],
    description: "Add a new route, component, or API handler",
    steps: [
      { order: 1, action: "Detect framework", command: "Check for next.config, vite.config, remix.config, express/fastify imports", validate: "Framework identified" },
      { order: 2, action: "Study existing route/component pattern", command: "Read an existing similar file for style reference" },
      { order: 3, action: "Check routing convention", command: "File-based (Next/Nuxt/Remix) vs config-based (React Router/Express)" },
      { order: 4, action: "Create the file", command: "Follow framework convention for file location and naming" },
      { order: 5, action: "Wire routing if needed", command: "For config-based routing: add route entry. For file-based: correct placement is enough" },
      { order: 6, action: "Add types/interfaces", command: "Define props, request/response types following project patterns" },
      { order: 7, action: "Test", command: "Visit the route or call the endpoint", validate: "Renders/responds correctly" },
      { order: 8, action: "Add tests", command: "Write tests following existing test patterns in the project" },
    ],
  },
]
