export { detectLanguage } from "./language-detector"
export { routeLanguage, formatLanguageContext, formatFailureContext } from "./language-router"
export { createLanguageIntelligenceHook } from "./language-intelligence-hook"
export type { LanguageProfile, LanguagePack, Stepbook, StepbookStep, FailureSignature, LanguageRouteResult } from "./types"
export { pythonPack } from "./packs/python"
export { typescriptPack } from "./packs/typescript"
export { pythonStepbooks } from "./stepbooks/python-stepbooks"
export { typescriptStepbooks } from "./stepbooks/typescript-stepbooks"
