import { writeFile } from "node:fs/promises"
import { join } from "node:path"
import type { AuditReport } from "./types"

const ROOT_DIR = process.cwd()
const FUNCTIONS_DIR = join(ROOT_DIR, "docs", "self-audit", "functions")

export async function writeFunctionReport(report: AuditReport): Promise<void> {
  const filename = `${report.functionId.replace(/[\/:]/g, "_")}.txt`
  const filepath = join(FUNCTIONS_DIR, filename)
  
  const content = [
    `# Function Audit Report`,
    `Function ID: ${report.functionId}`,
    `File Path: ${report.filePath}`,
    `Function Name: ${report.functionName}`,
    `Signature: ${report.signature || "N/A"}`,
    `Timestamp: ${report.timestamp}`,
    `Commit SHA (Before): ${report.commitShaBefore}`,
    `Commit SHA (After): ${report.commitShaAfter || "No change"}`,
    ``,
    `## Function Purpose`,
    report.purpose,
    ``,
    `## Caller/Context Summary`,
    report.callerContext,
    ``,
    `## Pre-Audit Findings`,
    `### Correctness/Bug Risk`,
    report.preAuditFindings.correctness,
    ``,
    `### Performance`,
    report.preAuditFindings.performance,
    ``,
    `### Code Health`,
    report.preAuditFindings.codeHealth,
    ``,
    `## Changes Made`,
    `### Bug Fix`,
    report.changes.bugFix || "No correctness issue found",
    ``,
    `### Performance Improvement`,
    report.changes.performanceImprovement || "No meaningful performance issue found",
    ``,
    `### Code Health Improvement`,
    report.changes.codeHealthImprovement || "No code health improvements needed",
    ``,
    `## Verification`,
    `### Tests/Checks Run`,
    ...report.verification.testsRun.map(test => `- ${test}`),
    ``,
    `### Before Result`,
    report.verification.beforeResult,
    ``,
    `### After Result`,
    report.verification.afterResult,
    ``,
    `## Files Changed`,
    report.filesChanged.length > 0 
      ? report.filesChanged.map(file => `- ${file}`).join("\n")
      : "No files changed",
    ``,
    `## Final Status`,
    report.finalStatus,
    ``,
    `---`,
    `Generated by oh-my-opencode self-audit loop`
  ].join("\n")
  
  await writeFile(filepath, content)
}
